### PR TITLE
Fixed xml so it works with Oreo and UE 4.21.

### PR DESCRIPTION
**Pull request by Burnrate**
Fixed xml so it works with Oreo and UE 4.21.  Couldn't get the functions to work as expected so far but it compiles, packages, and deploys successfully.

### CODE REVIEW

**Comment by Mosel3y** [comment]
@Burnrate Hey, thanks for the pull request. It has been working fine for me on 4.21, but now I'm thinking that I may have some uncommitted changes on my local version. I'll check in the next few days when I'm back at that PC, I'll merge your changes if so.

Regarding some functions not working as expected, you may need the READ_EXTERNAL_STORAGE permission set too. I hadn't added that as part of the plugin XML on the GitHub version since the extra permission isn't needed in all cases. I'll need to confirm that that could be the problem too though. 

Thanks!

**Comment by Burnrate** [comment]
Thanks :).  I had READ_EXTERNAL_STORAGE set but no luck.  I'm not sure if it has to do with Oreo, the S9 I am testing on, or something else.

I was changing up the engines layout settings in GameActivity.java.template, UEDeployAndroid.cs, and the three styles.xml files but I couldn't get things to work as expected.  I used lots of different combinations of changes and the plugin as well.  My goal was to show the status bar (without transparency and having it modify the available screen space) without the action bar.

It's most likely error on my part or my unfamiliarity with anything past API 21 (haven't done android in a while).  I'm going to keep looking into it next week and try some more methodical changes to eliminate variables.

**Comment by Burnrate** [comment]
I just saw this too,

UATHelper: Packaging (Android (Multi:ASTC,PVRTC,DXT,ATC,ETC2,ETC1a,ETC1)):   C:\...\Plugins\M3AndroidFunctions\Source\M3AndroidFunctions\M3AndroidFunctions.Build.cs: warning: Referenced directory 'C:\Program Files\Epic Games\UE_4.21\Engine\Source\AndroidFunctions\Public' does not exist.
PackagingResults: Warning: Referenced directory 'C:\Program Files\Epic Games\UE_4.21\Engine\Source\AndroidFunctions\Public' does not exist.

Haven't looked at it at all yet but wanted to post it here before I forgot.

**Comment by Mosel3y** [comment]
~~I believe that one is just a change in 4.21 but it doesn't cause any issues. I get that in a few projects,it's an easy fix though.~~ (Edit: just notices the paths is wrong so yep)

I'm going to look at the other things today - just haven't had a chance since I came back to work.

I think there has been changes to how the status bar/action bar work at the api level since I made the plugin indeed. I haven't tried it on phones like the S9/S10 which don't have physical buttons, it will probably need some tweaks to work properly for all devices.

**Comment by Mosel3y** [comment]
I got the same package failure as you, and your commit fixed it so thanks!

On the other issue with the status bar, this is working fine for me. 
For the set status bar visibility node to work, you have to Show Status Bar set to true in Project Settings>Plugins>M3 Android Functions, after that you can use the set status bar node to hide it again.

Is that what you are doing? If that isn't working for you, I can send you a test proejct were it works for me, to confirm it could be an issue with the S9. I'm testing on an S7.

**Comment by Burnrate** [comment]
I updated my android ndk to r15c from r14b which was installed with the NVIDIA Codeworks 1R7u1.  NVIDIA says 1R7u1 supports API 26 and r15c so everything should be good with that.  It all builds and runs but still no luck even with editing the themes in the engine defaults and using the project settings and/or BP nodes.

I think it might be because of the hidden action bar so you can't bring out the status bar without it.  That's how it looks to me anyways but I'm no expert.

I'll try out the test project to make sure I don't have something weird going on for sure.

**Comment by Mosel3y** [comment]
Sure, here's the link to the apk: https://www.dropbox.com/s/fbzt69i7rzc4ekj/AndroidFunctions-armv7-es2.apk?dl=0

I guess try that first and see what happens, let me know. If you'd rather have the project itself I can zip that up too, but, I'd be interested to see how this app runs on your device. If you just check what happens when you tap Hide Status Bar, or Show Status Bar

**Comment by Burnrate** [comment]
It will show and hide the status bar well.  The action bar is always present.  Also when the status bar is shown it will cover some of the app.  Works the same in both landscape and portrait.

**Pull request merged**
